// Wisecrack sound helper.
// Usage:  import { playSound, setMuted, setVolume } from './sounds.js';
//         playSound('dome-lift');
//
// Put the sounds/ folder somewhere your app serves as static files
// (in a Vite or Create React App project, that's the public/ folder),
// then set SOUND_FOLDER to match.

const SOUND_FOLDER = '/sounds/';

// Each sound's own loudness, so quiet ticks and big fanfares sit well together.
const SOUNDS = {
  'button-press': 0.7,
  'button-hover': 0.35,
  'select': 0.6,
  'popup-open': 0.6,
  'popup-close': 0.55,
  'toast': 0.5,
  'dome-lift': 0.6,
  'cookie-crack': 0.8,
  'cookie-break': 0.8,
  'progress-munch': 0.6,
  'slip-pickup': 0.6,
  'drop-approved': 0.7,
  'drop-faulty': 0.7,
  'timer-tick': 0.5,
  'time-up': 0.7,
  'coin-gain': 0.6,
  'coin-loss': 0.55,
  'star-earn': 0.65,
  'level-done': 0.75,
  'balloon-pop': 0.8,
  'highlight-remove': 0.5,
  'torch-swipe': 0.55,
  'step-a': 0.6,
  'step-b': 0.6,
};

// Sounds that aren't .mp3 - generated by scripts/make-sounds.js (run it again to
// tweak them): a fortune-cookie crack, a card swipe, and the marker loop below.
const FILES = {
  'step-a': 'step-a.wav',
  'step-b': 'step-b.wav',
  'cookie-crack': 'cookie-crack.wav',
  'torch-swipe': 'torch-swipe.wav',
  'highlight-stroke': 'highlight-stroke.wav',
};

// Looping sounds whose loudness follows what the player is doing (startLoop below),
// with their own top volume.
const LOOPS = {
  'highlight-stroke': 0.6, // broad marker on paper, while dragging to mark
};

let muted = false;
let masterVolume = 1;
const cache = {};

try {
  muted = localStorage.getItem('wisecrack-muted') === 'true';
} catch (e) { /* storage unavailable: start unmuted */ }

function load(name) {
  if (!cache[name]) {
    const audio = new Audio(SOUND_FOLDER + (FILES[name] || name + '.mp3'));
    audio.preload = 'auto';
    cache[name] = audio;
  }
  return cache[name];
}

// Load everything up front so the first play isn't delayed.
export function preloadSounds() {
  Object.keys(SOUNDS).forEach(load);
}

export function playSound(name) {
  if (muted || !(name in SOUNDS)) return;
  // Clone so the same sound can overlap itself (e.g. fast button taps).
  const audio = load(name).cloneNode();
  audio.volume = Math.min(1, SOUNDS[name] * masterVolume);
  audio.play().catch(() => { /* browser blocked audio before the first click: ignore */ });
}

// A sound that repeats seamlessly until stopped, with a loudness the game can change
// as it plays - e.g. the marker sound, louder the faster the player drags:
//   const loop = startLoop('highlight-stroke');
//   loop.setLevel(0..1);   // eases to that loudness
//   loop.stop();           // fades out
// Uses Web Audio (an <audio> element can't loop without a gap).
let audioCtx = null;
const decoded = {};

function context() {
  const Ctx = window.AudioContext || window.webkitAudioContext;
  if (!Ctx) return null;
  if (!audioCtx) audioCtx = new Ctx();
  if (audioCtx.state === 'suspended') audioCtx.resume().catch(() => {});
  return audioCtx;
}

function decode(name) {
  const ctx = context();
  if (!ctx) return Promise.reject(new Error('no Web Audio'));
  if (!decoded[name]) {
    decoded[name] = fetch(SOUND_FOLDER + (FILES[name] || name + '.mp3'))
      .then(res => res.arrayBuffer())
      .then(data => new Promise((resolve, reject) => ctx.decodeAudioData(data, resolve, reject)));
    decoded[name].catch(() => { delete decoded[name]; });
  }
  return decoded[name];
}

// Fetch a loop ahead of time so it starts instantly
export function preloadLoop(name) {
  if (name in LOOPS) decode(name).catch(() => {});
}

export function startLoop(name) {
  const ctx = muted || !(name in LOOPS) ? null : context();
  if (!ctx) return { setLevel() {}, stop() {} };
  const gain = ctx.createGain();
  gain.gain.value = 0;
  gain.connect(ctx.destination);
  let source = null;
  let stopped = false;
  decode(name).then(buffer => {
    if (stopped) return;
    source = ctx.createBufferSource();
    source.buffer = buffer;
    source.loop = true;
    source.connect(gain);
    source.start();
  }).catch(() => { /* couldn't load: stay silent */ });
  return {
    setLevel(level) {
      if (stopped) return;
      const target = Math.max(0, Math.min(1, level)) * LOOPS[name] * masterVolume;
      gain.gain.setTargetAtTime(muted ? 0 : target, ctx.currentTime, 0.035);
    },
    stop() {
      if (stopped) return;
      stopped = true;
      gain.gain.setTargetAtTime(0, ctx.currentTime, 0.04);
      setTimeout(() => {
        try { if (source) source.stop(); } catch (e) { /* already stopped */ }
        gain.disconnect();
      }, 300);
    },
  };
}

const muteListeners = new Set();

export function setMuted(value) {
  muted = value;
  try { localStorage.setItem('wisecrack-muted', String(value)); } catch (e) { /* ignore */ }
  muteListeners.forEach(fn => fn(value));
}

// Lets long-running audio (the ambient music) follow the mute button too.
// Returns an unsubscribe function.
export function onMuteChange(fn) {
  muteListeners.add(fn);
  return () => muteListeners.delete(fn);
}

export function isMuted() {
  return muted;
}

export function setVolume(value) {
  masterVolume = Math.max(0, Math.min(1, value));
}
